prices/food/urls.py
from django.conf.urls import url

from . import views

app_name = 'food'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^Proveedores/$', views.proveedorListView.as_view(), name='proveedor'),
    url(r'^Proveedores/(?P<pk>\d+)$', views.ProveedorDetailView.as_view(), name='proveedor-detail'),
    url(r'^Compradores/$', views.CompradorListView.as_view(), name='comprador'),
    url(r'^Comprador/(?P<pk>\d+)$', views.CompradorDetailView.as_view(), name='comprador-detail'),
    url(r'^Producto/$', views.ProductoListView.as_view(), name='producto'),
    url(r'^Producto/SC$', views.ProductoSCListView.as_view(), name='producto_sc'),
    url(r'^Producto/(?P<pk>\d+)$', views.ProductoDetailView.as_view(), name='producto-detail'),
    url(r'^Extraccion/Facturas/Ordenes$', views.request_page, name='persistir_facturas'),
    url(r'^Extraccion/Proveedor/$', views.ExtraerOrdenesCompra, name='extraccion_proveedor'),
    url(r'^Extraccion/Proveedor/Codigos$', views.Codigos_Proveedores, name='lista_proveedor_extract'),
    url(r'^Extraccion/Facturas/$', views.ExtraerFacturas, name='extraccion_facturas'),
    url(r'^Ordenes/Compra/$', views.lista_ordenes, name='listar_ordenes'),
    url(r'^Region/$', views.RegionListView.as_view(), name='region'),
    url(r'^Categorias/$', views.CategoriaListView.as_view(), name='categorias'),
    url(r'^Listar/Ordenes/(?P<orden>\d+)/$', views.detalle_ordenescompra, name='detalle_factura'),
    #
    url(r'^Listar/Ordenes$', views.ListarOrdenesCompraxFecha, name='Listar_Ordenes'),
    url(r'^Productos/Graficos$', views.listaproductografica, name='grafica_producto'),
    url(r'^Productos/Graficos/Clientes/(?P<pk>\d+)$', views.grafica_producto_cliente, name='grafica_producto_cliente'),
    url(r'^Productos/Graficos/(?P<pk>\d+)$', views.productgraphic, name='grafico'),
    url(r'^Productos/Top_10$', views.top_ten, name='top_10'),
    url(r'^Productos/Top_Segmentados$', views.mayor_segmentacion, name='top_10_segmenta'),
    url(r'^Productos/ListaBase$', views.lista_base_load, name='add_lista_base'),
    url(r'^Productos/ListaBase/view$', views.lista_base_view, name='view_lista_base'),
    url(r'^Productos/ListaBase/update$', views.lista_base_update, name='update_lista_base'),
    url(r'^Productos/Productos/cotejo$', views.cotejo_producto_lista_base, name='cotejo_producto_lista_base'),
    url(r'^Productos/Precio_Sugerido$', views.possible_price, name='sugiere_precios'),
    url(r'^Productos/Listar_Sugeridos$', views.list_price_sugg, name='lista_precios_sugeridos'),
    # lista_proveedor_extract
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'), grafica_producto_cliente update_lista_base
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'), add_lista_base
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

prices/prices/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^food/', include('food.urls')),
    # url(r'^', include('food.urls', namespace='food')),

    url(r'^admin/', admin.site.urls),
    url(r'^food/', include('food.urls', namespace='food')),
]

prices/food/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

prices/food/forms.py
from django import forms
from django.forms import widgets
from django.forms.widgets import CheckboxSelectMultiple

from  Modelos.Facturas.models import Facturas
from Modelos.Proveedor.models import *


"""
def get_categorized_skills(): 
    skills = {} 
    for s in Skill.objects.values('pk', 'name', 'category__name').order_by('category__name'): 
     if s['category__name'] not in skills.keys(): 
      skills[s['category__name']] = [] 
     skills[s['category__name']].append((s['pk'], s['name'])) 
    return skills 

class SkillSelectionForm(forms.Form): 
    def __init__(self, *args, **kwargs): 
     super(SkillSelectionForm, self).__init__(*args, **kwargs) 
     skills = get_categorized_skills() 
     for idx, cat in enumerate(skills.keys()): 
      field_name = u'category-{0}'.format(idx) 
      display_name = cat 
      self.fields[field_name] = forms.MultipleChoiceField(choices=skills[cat], widget=forms.CheckboxSelectMultiple, label=display_name) 
"""
def get_categorized_skills():
    codProv = {}
    # xNomProv = []
    for s in Proveedor.objects.values('id','CodigoProveedor','NombreProveedor').order_by('CodigoProveedor'):
        if s['CodigoProveedor'] not in codProv.keys():
            codProv[s['CodigoProveedor']]=[]
            # xNomProv.append(s['NombreProveedor'])
        codProv[s['CodigoProveedor']].append((s['CodigoProveedor'], s['CodigoProveedor']+' - '+s['NombreProveedor']))
    return codProv


class ConsultaProveedorForms(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ConsultaProveedorForms, self).__init__(*args, **kwargs)
        skills = get_categorized_skills()
        # self.CodigosProveedor = ''
        for idx, cat in enumerate(skills.keys()):
            field_name = 'codigo-{0}'.format(idx)
            self.fields[field_name] = forms.MultipleChoiceField(required = False , choices= skills[cat],
                                                                widget=forms.CheckboxSelectMultiple, label='')

    FechaInicio = forms.DateField(widget=forms.SelectDateWidget(),label='Fecha Inicio')
    FechaFin = forms.DateField(widget = forms.SelectDateWidget(),label='Fecha Fin')
    CodigosProveedor = forms.CharField(widget=forms.Textarea, required=False, label='Cod. de Proveedores')

class ListarOrdenesExtraidasxFechaForms(forms.Form):
    FechaInicio = forms.DateField(widget=forms.SelectDateWidget(),label='Fecha Inicio')
    FechaFin = forms.DateField(widget = forms.SelectDateWidget(),label='Fecha Fin')

class ConsultaFacturasForms(forms.ModelForm):

     class Meta:
         model=Facturas

         fields = [
             'CodigoOrdenCompra',
             'CodigoProveedor',
              'Fecha',
         ]

         labels = {
             'CodigoOrdenCompra': 'Codigo de la Orden de Compra',
             'CodigoProveedor': 'Codigo del Proveedor',
             'Fecha': 'Fecha de Emision',
         }

         widgets = {
             'CodigoOrdenCompra': forms.TextInput(attrs={'class':'form-control'}),
             'CodigoProveedor': forms.TextInput(attrs={'class':'form-control'}),
             'Fecha': forms.TextInput(attrs={'class':'form-control'}),
         }

prices/food/views.py
import random
import operator
import time
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages
import codecs

from django.shortcuts import render

from Modelos.Comprador.models import Comprador
from Modelos.Proveedor.models import Proveedor
from Modelos.Producto.models import Producto
from Modelos.Facturas.models import Facturas
from Modelos.Detalle.models import *
from  Modelos.Categoria.models import *
from  Modelos.Region.models import *
from Modelos.Formato.models import *
from Modelos.ListaBase.models import *

from django.views import generic

from food.Extraccion import *
import json

from datetime import datetime,timedelta

# Para los formularios
from django.template import RequestContext
from food.forms import ConsultaProveedorForms,ConsultaFacturasForms, ListarOrdenesExtraidasxFechaForms
from django.shortcuts import render_to_response, redirect, HttpResponseRedirect


# Create your views here. unicode(xDesSC, errors='ignore')





def index(request):
     # Genera contadores de algunos de los objetos principales
    num_proveedores = Proveedor.objects.all().count()
    num_compradores = Comprador.objects.all().count()
    num_detalles = Producto.objects.all().count()
    image_logo = open("food/images/Logo_FoodSys.png", "rb").read()
    #  Lanzaremos aqui los hilos para extraccion automatica (tambien actualizar lista de precios sugeridos)

    # Renderiza la plantilla HTML index.html con los datos en la variable contexto
    return render(
        request,
        'index.html',
        context={'num_proveedores': num_proveedores, 'num_compradores': num_compradores, 'num_detalles': num_detalles, 'image_logo':image_logo},
    )


def detalle_ordenescompra(request,orden):
    regFactura = Facturas.objects.filter(id = orden, EstadoExtraccion=True)
    # p = request.GET.get('page')
    # print('\nget_page: %s  ===  \n' % p)
    if regFactura:
        detalle = []
        regFactura = regFactura[0]
        regDetalle = Detalle.objects.filter(CodigoOrdenCompra = regFactura.CodigoOrdenCompra)
        contexto = {'factura': regFactura, 'detalle':''}
        if regDetalle:
            xdetalle = Detalle()
            for regd in regDetalle:
                detalle.append(regd)
            contexto = {'factura': regFactura, 'detalle':detalle}
    else:
        contexto = {}
    return render(request, 'DetallesOrdenCompra/detalle_ordenescompra.html', contexto)

def request_page(request):
    xurlbase='http://api.mercadopublico.cl/servicios/v1/publico/ordenesdecompra.json?'
    ticket='&ticket=C74E17AB-BB1C-4CD2-9495-C55A5D2A2E56'
    urlbase = 'http://api.mercadopublico.cl/servicios/v1/publico/ordenesdecompra.json?'
    urlbase += 'codigo='
    tTotalFacturas = 0
    dib = ['|', '/', '-', '|', '\\']
    contexto = {'num': 0}
    tiempo = [-1,0]
    if (request.GET.get('boton')):
        xIntentos = True

        if len(ListaBase.objects.all())>1: #.order_by('Fecha')
            Nerror = 0
            # fout = codecs.open('files/PorClasificar'+str(len(Facturas.objects.filter(EstadoExtraccion=False)))+'.txt', "w",encoding='utf-8', errors='ignore')
            while xIntentos:
                facturas = Facturas.objects.filter(EstadoExtraccion=False).order_by('Fecha') # Solo las facturas que aun no se han extraido
                # tTotalFacturas = len(facturas)
                xIntentos = xIntentos + 1
                cExtract = 0
                kInd = -1
                if facturas:
                    for orden in facturas:
                        url = urlbase+orden.CodigoOrdenCompra.replace("\n","")+ticket
                        xFecha = orden.Fecha
                        xOrdenCompra = orden.CodigoOrdenCompra
                        if Nerror >= 10:  # tiempo = [-1,0]  connect and read
                            if Nerror % 10:
                                tiempo[0] += 5
                                tiempo[1] = 10
                            Json, code = Scrapy(url,tiempo)
                        else:
                            Json, code = Scrapy(url, tiempo)
                        if code != -1:
                            Nerror += 1
                            # print('\nError code = %s  Nerrores %s' % (code,Nerror))
                        # print('\nURL BAse: %s' % url)
                        # print('\nJson = %s ' % Json)
                        if Json:
                            # kInd = kInd + 1
                            # if kInd >= len(dib):
                            #     kInd = 0
                            # mensa = 'Proccess {}'.format(dib[kInd])
                            # messages.success(request, mensa)
                            cExtract = cExtract + 1
                            regReg = Region.objects.filter( DescripcionRegion = (Json['Listado'][0]['Comprador']['RegionUnidad']).replace("\n","") ) #Region
                            if not regReg:
                                region = Region()
                                region.DescripcionRegion = (Json['Listado'][0]['Comprador']['RegionUnidad']).replace("\n","")
                                region.CodigoRegion = '{}'.format(len(Region.objects.all()))
                                region.save()
                                idregion=region.id
                            else:
                                idregion = regReg[0].id
                            regFact = Facturas.objects.filter(CodigoOrdenCompra = orden.CodigoOrdenCompra) # Facturas
                            if regFact:
                                region = ''
                                regFactura = regFact[0]
                                regFactura.CodigoOrganismoComprador = Json['Listado'][0]['Comprador']['CodigoOrganismo']
                                regFactura.CodigoRegion =  '{}'.format(idregion) #Json['Listado'][0]['Comprador']['RegionUnidad']#RegionUnidad
                                regFactura.TotalFactura = Json['Listado'][0]['TotalNeto']
                                regFactura.EstadoExtraccion = True
                                xSave = False # Solo Comprador
                                regComprador = Comprador.objects.filter(CodigoOrganismoComprador = Json['Listado'][0]['Comprador']['CodigoOrganismo']) # Comprador
                                if not regComprador:
                                    regComprador = Comprador()
                                    regComprador.CodigoOrganismoComprador = Json['Listado'][0]['Comprador']['CodigoOrganismo']
                                    regComprador.NombreOrganismoComprador = Json['Listado'][0]['Comprador']['NombreOrganismo']
                                    regComprador.RutUnidadComprador = Json['Listado'][0]['Comprador']['RutUnidad']
                                    regComprador.ActividadComprador = Json['Listado'][0]['Comprador']['Actividad']
                                    regComprador.DireccionUnidadComprador = Json['Listado'][0]['Comprador']['DireccionUnidad']
                                    regComprador.NombreContactoComprador = Json['Listado'][0]['Comprador']['NombreContacto']
                                    regComprador.CargoContactoComprador = Json['Listado'][0]['Comprador']['CargoContacto']
                                    if len(Json['Listado'][0]['Comprador']['FonoContacto'][:79])>80:
                                        xContact = Json['Listado'][0]['Comprador']['FonoContacto'][:79]
                                    else:
                                        xContact = Json['Listado'][0]['Comprador']['FonoContacto']
                                    regComprador.FonoContactoComprador = xContact
                                    regComprador.MailContactoComprador = Json['Listado'][0]['Comprador']['MailContacto']
                                    xSave = True
                                else:
                                    regComprador = regComprador[0]
                                regReg = Region.objects.filter(DescripcionRegion=(Json['Listado'][0]['Proveedor']['Region']).replace("\n", ""))
                                if not regReg:
                                    region = Region()
                                    region.DescripcionRegion = (Json['Listado'][0]['Proveedor']['Region']).replace("\n", "")
                                    region.CodigoRegion = '{}'.format(len(Region.objects.all()))
                                    region.save()
                                else:
                                    region = regReg[0]
                                regProveedor = Proveedor.objects.filter(CodigoProveedor=Json['Listado'][0]['Proveedor']['Codigo'])  # Proveedor
                                if not regProveedor:
                                    regProveedor = Proveedor()
                                    regProveedor.CodigoProveedor = Json['Listado'][0]['Proveedor']['Codigo']
                                    regProveedor.NombreProveedor = Json['Listado'][0]['Proveedor']['Nombre']
                                    regProveedor.ActividadProveedor = Json['Listado'][0]['Proveedor']['Actividad']
                                    regProveedor.RutSucursalProveedor = Json['Listado'][0]['Proveedor']['RutSucursal']
                                    regProveedor.DireccionProveedor = Json['Listado'][0]['Proveedor']['Direccion']
                                    regProveedor.NombreContactoProveedor = Json['Listado'][0]['Proveedor']['NombreContacto']
                                    regProveedor.CargoContactoProveedor = Json['Listado'][0]['Proveedor']['CargoContacto']
                                    regProveedor.FonoContactoProveedor = Json['Listado'][0]['Proveedor']['FonoContacto'][:79]
                                    regProveedor.MailContactoProveedor = Json['Listado'][0]['Proveedor']['MailContacto']
                                    regProveedor.regionPk = region

prices/food/templates/DetallesOrdenCompra/detalle_ordenescompra.html
{% extends "Plantilla_Index.html" %}

{% block content %}
{% block title %}<title>Detalles Ordenes de Compra</title>{% endblock %}
<H1 align="center">Detalle Orden de Compra</H1>
  <div style="margin-left:20px;margin-top:20px">
      <div>
          {% if factura %}
          <p> Código de Factura: <a href="">{{ factura.CodigoOrdenCompra }}</a></p>
            <p> Proveedor: {{ factura.proveedorFk.NombreProveedor }}</p>
            <p> Comprador:  {{ factura.compradorFk.NombreOrganismoComprador }}</p>
            <p> Fecha Emisión:  {{ factura.Fecha }}</p>
          {% endif %}
      </div>
      <table class="table table-bordered">
          <thead>
          <tr>
              <td>#</td>
              <td>Producto</td>
              <td>Formato</td>
              <td>Cantidad</td>
              <td>Precio Neto</td>
          </tr>
          </thead>
          <tbody>
          {% if detalle %}
            {% for detail in detalle %}
             <tr>
                 <td>{{ forloop.counter0 }}</td>
                <td>{{ detail.productoFk.DescripcionProducto }}</td>
                 <td>{{ detail.productoFk.formatoFk.DescripcionFormato }}</td>
                <td>{{ detail.Cantidad }}</td>
                <td>{{ detail.PrecioNeto }}</td>
             </tr>
            {% endfor %}
            <tr>
                 <td><strong>Total Facturado: </strong></td>
                <td></td>
                <td></td>
                <td></td>
                <td>{{ factura.TotalFactura }}</td>
             </tr>
          {% else %}
           <h1> !!! No hay Detalle en Factura Disponibles !!!!</h1>
          {% endif %}
          </tbody>
      </table>

  </div>
{% endblock %}

<!--
    CodigoCategoria = models.CharField(blank=True,max_length=50)
    categoriaFk = models.ForeignKey(Categoria, null= True, blank= True, on_delete = models.CASCADE)
    CodigoProducto = models.CharField(max_length=50)
    DescripcionProducto = models.CharField(blank=True,max_length=80)
    PrecioCosto = models.FloatField(default=0)
    PrecioMin = models.FloatField(default=0)
    PrecioMedio = models.FloatField(default=0)
    PrecioMax = models.FloatField(default=0)
    FechaModifica = models.DateField()
    formatoFk = models.ForeignKey(Formato, null= True, blank= True, on_delete = models.CASCADE)
    Activo = models.BooleanField(default = True)
-->

prices/food/templates/DetallesOrdenCompra/lista_ordenesxfecha.html
{% extends "Plantilla_Index.html" %}

{% block content %}
{% block title %}<title>Listar Ordenes por Rango de Fechas</title>{% endblock %}
<H1 align="center">Listado de Ordenes de Compra</H1>
  <div style="margin-left:20px;margin-top:20px">
      <table class="table table-bordered">

          <thead>
          <tr>
              <td>#</td>
              <td>Código de Orden</td>
              <td>Código del Proveedor</td>
              <td>Fecha de Emisión</td>
          </tr>
          </thead>
          <tbody>
          {% if ordenes %}
            {% for orden in ordenes %}
             <tr>
                 <td>{{ forloop.counter0 }}</td>
                <td><a href="{% url 'food:detalle_factura'  orden.id %}">{{ orden.CodigoOrdenCompra }}</a></td>
                <td>{{ orden.proveedorFk.NombreProveedor }}</td>
                <td>{{ orden.Fecha }}</td>
             </tr>
            {% endfor %}
          {% else %}
           <h1> !!! No hay Ordenes de Compra Disponibles !!!!</h1>
          {% endif %}
          </tbody>
      </table>

  </div>
{% endblock %}

prices/food/templates/DetallesOrdenCompra/listar_ordenes.html
{% extends "Plantilla_Index.html" %}

{% block content %}
{% block title %}<title>Listar Ordenes por Rango de Fechas</title>{% endblock %}
<H1 align="center">Ordenes Extraidas</H1>
  <div style="margin-left:20px;margin-top:20px">
      <h4>    </h4>
      <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Listar Ordenes</button>
     </form>
      {% if Err %}
          <h4> {{ Err }}   </h4>
      {% endif %}
   </div>

{% endblock %}