prices/food/urls.py
from django.conf.urls import url

from . import views

app_name = 'food'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^Proveedores/$', views.proveedorListView.as_view(), name='proveedor'),
    url(r'^Proveedores/(?P<pk>\d+)$', views.ProveedorDetailView.as_view(), name='proveedor-detail'),
    url(r'^Compradores/$', views.CompradorListView.as_view(), name='comprador'),
    url(r'^Comprador/(?P<pk>\d+)$', views.CompradorDetailView.as_view(), name='comprador-detail'),
    url(r'^Producto/$', views.ProductoListView.as_view(), name='producto'),
    url(r'^Producto/SC$', views.ProductoSCListView.as_view(), name='producto_sc'),
    url(r'^Producto/(?P<pk>\d+)$', views.ProductoDetailView.as_view(), name='producto-detail'),
    url(r'^Extraccion/Facturas/Ordenes$', views.request_page, name='persistir_facturas'),
    url(r'^Extraccion/Proveedor/$', views.ExtraerOrdenesCompra, name='extraccion_proveedor'),
    url(r'^Extraccion/Proveedor/Codigos$', views.Codigos_Proveedores, name='lista_proveedor_extract'),
    url(r'^Extraccion/Facturas/$', views.ExtraerFacturas, name='extraccion_facturas'),
    url(r'^Ordenes/Compra/$', views.lista_ordenes, name='listar_ordenes'),
    url(r'^Region/$', views.RegionListView.as_view(), name='region'),
    url(r'^Categorias/$', views.CategoriaListView.as_view(), name='categorias'),
    url(r'^Listar/Ordenes/(?P<orden>\d+)/$', views.detalle_ordenescompra, name='detalle_factura'),
    #
    url(r'^Listar/Ordenes$', views.ListarOrdenesCompraxFecha, name='Listar_Ordenes'),
    url(r'^Productos/Graficos$', views.listaproductografica, name='grafica_producto'),
    url(r'^Productos/Graficos/Clientes/(?P<pk>\d+)$', views.grafica_producto_cliente, name='grafica_producto_cliente'),
    url(r'^Productos/Graficos/(?P<pk>\d+)$', views.productgraphic, name='grafico'),
    url(r'^Productos/Top_10$', views.top_ten, name='top_10'),
    url(r'^Productos/Top_Segmentados$', views.mayor_segmentacion, name='top_10_segmenta'),
    url(r'^Productos/ListaBase$', views.lista_base_load, name='add_lista_base'),
    url(r'^Productos/ListaBase/view$', views.lista_base_view, name='view_lista_base'),
    url(r'^Productos/ListaBase/update$', views.lista_base_update, name='update_lista_base'),
    url(r'^Productos/Productos/cotejo$', views.cotejo_producto_lista_base, name='cotejo_producto_lista_base'),
    url(r'^Productos/Precio_Sugerido$', views.possible_price, name='sugiere_precios'),
    url(r'^Productos/Listar_Sugeridos$', views.list_price_sugg, name='lista_precios_sugeridos'),
    # lista_proveedor_extract
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'), grafica_producto_cliente update_lista_base
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'), add_lista_base
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

prices/prices/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^food/', include('food.urls')),
    # url(r'^', include('food.urls', namespace='food')),

    url(r'^admin/', admin.site.urls),
    url(r'^food/', include('food.urls', namespace='food')),
]

prices/food/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

prices/food/forms.py
from django import forms
from django.forms import widgets
from django.forms.widgets import CheckboxSelectMultiple

from  Modelos.Facturas.models import Facturas
from Modelos.Proveedor.models import *


"""
def get_categorized_skills(): 
    skills = {} 
    for s in Skill.objects.values('pk', 'name', 'category__name').order_by('category__name'): 
     if s['category__name'] not in skills.keys(): 
      skills[s['category__name']] = [] 
     skills[s['category__name']].append((s['pk'], s['name'])) 
    return skills 

class SkillSelectionForm(forms.Form): 
    def __init__(self, *args, **kwargs): 
     super(SkillSelectionForm, self).__init__(*args, **kwargs) 
     skills = get_categorized_skills() 
     for idx, cat in enumerate(skills.keys()): 
      field_name = u'category-{0}'.format(idx) 
      display_name = cat 
      self.fields[field_name] = forms.MultipleChoiceField(choices=skills[cat], widget=forms.CheckboxSelectMultiple, label=display_name) 
"""
def get_categorized_skills():
    codProv = {}
    # xNomProv = []
    for s in Proveedor.objects.values('id','CodigoProveedor','NombreProveedor').order_by('CodigoProveedor'):
        if s['CodigoProveedor'] not in codProv.keys():
            codProv[s['CodigoProveedor']]=[]
            # xNomProv.append(s['NombreProveedor'])
        codProv[s['CodigoProveedor']].append((s['CodigoProveedor'], s['CodigoProveedor']+' - '+s['NombreProveedor']))
    return codProv


class ConsultaProveedorForms(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ConsultaProveedorForms, self).__init__(*args, **kwargs)
        skills = get_categorized_skills()
        # self.CodigosProveedor = ''
        for idx, cat in enumerate(skills.keys()):
            field_name = 'codigo-{0}'.format(idx)
            self.fields[field_name] = forms.MultipleChoiceField(required = False , choices= skills[cat],
                                                                widget=forms.CheckboxSelectMultiple, label='')

    FechaInicio = forms.DateField(widget=forms.SelectDateWidget(),label='Fecha Inicio')
    FechaFin = forms.DateField(widget = forms.SelectDateWidget(),label='Fecha Fin')
    CodigosProveedor = forms.CharField(widget=forms.Textarea, required=False, label='Cod. de Proveedores')

class ListarOrdenesExtraidasxFechaForms(forms.Form):
    FechaInicio = forms.DateField(widget=forms.SelectDateWidget(),label='Fecha Inicio')
    FechaFin = forms.DateField(widget = forms.SelectDateWidget(),label='Fecha Fin')

class ConsultaFacturasForms(forms.ModelForm):

     class Meta:
         model=Facturas

         fields = [
             'CodigoOrdenCompra',
             'CodigoProveedor',
              'Fecha',
         ]

         labels = {
             'CodigoOrdenCompra': 'Codigo de la Orden de Compra',
             'CodigoProveedor': 'Codigo del Proveedor',
             'Fecha': 'Fecha de Emision',
         }

         widgets = {
             'CodigoOrdenCompra': forms.TextInput(attrs={'class':'form-control'}),
             'CodigoProveedor': forms.TextInput(attrs={'class':'form-control'}),
             'Fecha': forms.TextInput(attrs={'class':'form-control'}),
         }

prices/food/views.py
import random
import operator
import time
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages
import codecs

from django.shortcuts import render

from Modelos.Comprador.models import Comprador
from Modelos.Proveedor.models import Proveedor
from Modelos.Producto.models import Producto
from Modelos.Facturas.models import Facturas
from Modelos.Detalle.models import *
from  Modelos.Categoria.models import *
from  Modelos.Region.models import *
from Modelos.Formato.models import *
from Modelos.ListaBase.models import *

from django.views import generic

from food.Extraccion import *
import json

from datetime import datetime,timedelta

# Para los formularios
from django.template import RequestContext
from food.forms import ConsultaProveedorForms,ConsultaFacturasForms, ListarOrdenesExtraidasxFechaForms
from django.shortcuts import render_to_response, redirect, HttpResponseRedirect


# Create your views here. unicode(xDesSC, errors='ignore')





def index(request):
     # Genera contadores de algunos de los objetos principales
    num_proveedores = Proveedor.objects.all().count()
    num_compradores = Comprador.objects.all().count()
    num_detalles = Producto.objects.all().count()
    image_logo = open("food/images/Logo_FoodSys.png", "rb").read()
    #  Lanzaremos aqui los hilos para extraccion automatica (tambien actualizar lista de precios sugeridos)

    # Renderiza la plantilla HTML index.html con los datos en la variable contexto
    return render(
        request,
        'index.html',
        context={'num_proveedores': num_proveedores, 'num_compradores': num_compradores, 'num_detalles': num_detalles, 'image_logo':image_logo},
    )


def detalle_ordenescompra(request,orden):
    regFactura = Facturas.objects.filter(id = orden, EstadoExtraccion=True)
    # p = request.GET.get('page')
    # print('\nget_page: %s  ===  \n' % p)
    if regFactura:
        detalle = []
        regFactura = regFactura[0]
        regDetalle = Detalle.objects.filter(CodigoOrdenCompra = regFactura.CodigoOrdenCompra)
        contexto = {'factura': regFactura, 'detalle':''}
        if regDetalle:
            xdetalle = Detalle()
            for regd in regDetalle:
                detalle.append(regd)
            contexto = {'factura': regFactura, 'detalle':detalle}
    else:
        contexto = {}
    return render(request, 'DetallesOrdenCompra/detalle_ordenescompra.html', contexto)

def request_page(request):
    xurlbase='http://api.mercadopublico.cl/servicios/v1/publico/ordenesdecompra.json?'
    ticket='&ticket=C74E17AB-BB1C-4CD2-9495-C55A5D2A2E56'
    urlbase = 'http://api.mercadopublico.cl/servicios/v1/publico/ordenesdecompra.json?'
    urlbase += 'codigo='
    tTotalFacturas = 0
    dib = ['|', '/', '-', '|', '\\']
    contexto = {'num': 0}
    tiempo = [-1,0]
    if (request.GET.get('boton')):
        xIntentos = True

        if len(ListaBase.objects.all())>1: #.order_by('Fecha')
            Nerror = 0
            # fout = codecs.open('files/PorClasificar'+str(len(Facturas.objects.filter(EstadoExtraccion=False)))+'.txt', "w",encoding='utf-8', errors='ignore')
            while xIntentos:
                facturas = Facturas.objects.filter(EstadoExtraccion=False).order_by('Fecha') # Solo las facturas que aun no se han extraido
                # tTotalFacturas = len(facturas)
                xIntentos = xIntentos + 1
                cExtract = 0
                kInd = -1
                if facturas:
                    for orden in facturas:
                        url = urlbase+orden.CodigoOrdenCompra.replace("\n","")+ticket
                        xFecha = orden.Fecha
                        xOrdenCompra = orden.CodigoOrdenCompra
                        if Nerror >= 10:  # tiempo = [-1,0]  connect and read
                            if Nerror % 10:
                                tiempo[0] += 5
                                tiempo[1] = 10
                            Json, code = Scrapy(url,tiempo)
                        else:
                            Json, code = Scrapy(url, tiempo)
                        if code != -1:
                            Nerror += 1
                            # print('\nError code = %s  Nerrores %s' % (code,Nerror))
                        # print('\nURL BAse: %s' % url)
                        # print('\nJson = %s ' % Json)
                        if Json:
                            # kInd = kInd + 1
                            # if kInd >= len(dib):
                            #     kInd = 0
                            # mensa = 'Proccess {}'.format(dib[kInd])
                            # messages.success(request, mensa)
                            cExtract = cExtract + 1
                            regReg = Region.objects.filter( DescripcionRegion = (Json['Listado'][0]['Comprador']['RegionUnidad']).replace("\n","") ) #Region
                            if not regReg:
                                region = Region()
                                region.DescripcionRegion = (Json['Listado'][0]['Comprador']['RegionUnidad']).replace("\n","")
                                region.CodigoRegion = '{}'.format(len(Region.objects.all()))
                                region.save()
                                idregion=region.id
                            else:
                                idregion = regReg[0].id
                            regFact = Facturas.objects.filter(CodigoOrdenCompra = orden.CodigoOrdenCompra) # Facturas
                            if regFact:
                                region = ''
                                regFactura = regFact[0]
                                regFactura.CodigoOrganismoComprador = Json['Listado'][0]['Comprador']['CodigoOrganismo']
                                regFactura.CodigoRegion =  '{}'.format(idregion) #Json['Listado'][0]['Comprador']['RegionUnidad']#RegionUnidad
                                regFactura.TotalFactura = Json['Listado'][0]['TotalNeto']
                                regFactura.EstadoExtraccion = True
                                xSave = False # Solo Comprador
                                regComprador = Comprador.objects.filter(CodigoOrganismoComprador = Json['Listado'][0]['Comprador']['CodigoOrganismo']) # Comprador
                                if not regComprador:
                                    regComprador = Comprador()
                                    regComprador.CodigoOrganismoComprador = Json['Listado'][0]['Comprador']['CodigoOrganismo']
                                    regComprador.NombreOrganismoComprador = Json['Listado'][0]['Comprador']['NombreOrganismo']
                                    regComprador.RutUnidadComprador = Json['Listado'][0]['Comprador']['RutUnidad']
                                    regComprador.ActividadComprador = Json['Listado'][0]['Comprador']['Actividad']
                                    regComprador.DireccionUnidadComprador = Json['Listado'][0]['Comprador']['DireccionUnidad']
                                    regComprador.NombreContactoComprador = Json['Listado'][0]['Comprador']['NombreContacto']
                                    regComprador.CargoContactoComprador = Json['Listado'][0]['Comprador']['CargoContacto']
                                    if len(Json['Listado'][0]['Comprador']['FonoContacto'][:79])>80:
                                        xContact = Json['Listado'][0]['Comprador']['FonoContacto'][:79]
                                    else:
                                        xContact = Json['Listado'][0]['Comprador']['FonoContacto']
                                    regComprador.FonoContactoComprador = xContact
                                    regComprador.MailContactoComprador = Json['Listado'][0]['Comprador']['MailContacto']
                                    xSave = True
                                else:
                                    regComprador = regComprador[0]
                                regReg = Region.objects.filter(DescripcionRegion=(Json['Listado'][0]['Proveedor']['Region']).replace("\n", ""))
                                if not regReg:
                                    region = Region()
                                    region.DescripcionRegion = (Json['Listado'][0]['Proveedor']['Region']).replace("\n", "")
                                    region.CodigoRegion = '{}'.format(len(Region.objects.all()))
                                    region.save()
                                else:
                                    region = regReg[0]
                                regProveedor = Proveedor.objects.filter(CodigoProveedor=Json['Listado'][0]['Proveedor']['Codigo'])  # Proveedor
                                if not regProveedor:
                                    regProveedor = Proveedor()
                                    regProveedor.CodigoProveedor = Json['Listado'][0]['Proveedor']['Codigo']
                                    regProveedor.NombreProveedor = Json['Listado'][0]['Proveedor']['Nombre']
                                    regProveedor.ActividadProveedor = Json['Listado'][0]['Proveedor']['Actividad']
                                    regProveedor.RutSucursalProveedor = Json['Listado'][0]['Proveedor']['RutSucursal']
                                    regProveedor.DireccionProveedor = Json['Listado'][0]['Proveedor']['Direccion']
                                    regProveedor.NombreContactoProveedor = Json['Listado'][0]['Proveedor']['NombreContacto']
                                    regProveedor.CargoContactoProveedor = Json['Listado'][0]['Proveedor']['CargoContacto']
                                    regProveedor.FonoContactoProveedor = Json['Listado'][0]['Proveedor']['FonoContacto'][:79]
                                    regProveedor.MailContactoProveedor = Json['Listado'][0]['Proveedor']['MailContacto']
                                    regProveedor.regionPk = region

prices/food/templates/Plantilla_Index.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% block title %}
         <title>Análisis de Precios </title>
    {% endblock %}




  <!-- Add additional CSS in static file  -->

  {% load static %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/Chart.js' %}"></script>


</head>

<!------ Include the above in your HEAD tag ---------->


<body>
<div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
         {% block sidebar %}
          <div class="wrapper">
              <a class="navbar-logo" href="#">
                 <img src="{% static 'images/Logo_FoodSys.png' %}" alt="Logo"/>
              </a>

              <div class="main_sidebar">
              <ul>
                <li><i class="fa fa-home"></i><a href="{% url 'food:index' %}">Home</a></li>
                <li><h2>Proveedores</h2></li>
                <li><i class="fa fa-bus"></i><a href="{% url 'food:proveedor' %}">Proveedores</a></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:extraccion_proveedor' %}">Extracción Ordenes (Prov)</a></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:lista_proveedor_extract' %}">Agregar Cod. Prov. Extrct. Automc.</a></li>
                  <li><i class="fas fa-leaf"></i><a href="{% url 'food:region' %}">Region</a></li>
                  <li><h2>Clientes</h2></li>
                <li><i class="fas fa-cart-arrow-down"></i><a href="{% url 'food:comprador' %}">Compradores</a></li>
                  <li><h2>Productos</h2></li>
                 <li><i class="fas fa-leaf"></i><a href="{% url 'food:producto' %}">List. Productos (Std)</a></li>
                 <li><i class="fas fa-leaf"></i><a href="{% url 'food:cotejo_producto_lista_base' %}">Cotejo Productos (Std - L.Base)</a></li>
                 <li><i class="fas fa-leaf"></i><a href="{% url 'food:producto_sc' %}">List. Productos sin Clasificar</a></li>

                 <li><i class="fas fa-leaf"></i><a href="{% url 'food:categorias' %}">Categorias</a></li>

                <li><h2>Extracción</h2></li>
                <li><i class="fa fa-search"></i><a href="{% url 'food:extraccion_facturas' %}">Extraer - Ordenes Disponibles</a></li>
                <li><i class="fa fa-search"></i><a href="{% url 'food:listar_ordenes' %}">Ordenes Disponibles Extracción</a></li>
                 <li><i class="fa fa-search"></i><a href="{% url 'food:Listar_Ordenes' %}">Listar Ordenes por Fecha</a></li>
                  <li><h2>Gráficas</h2></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:grafica_producto' %}?opcion=1">Gráficas de Productos</a></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:grafica_producto' %}?opcion=2">Gráficas de Prod. (Cliente)</a></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:top_10' %}">Top 10 (+ Vendidos)</a></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:top_10_segmenta' %}">Top 10 (+ Segmentados)</a></li>
                  <li><h2>Lista Base</h2></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:add_lista_base' %}">Agregar Lista Base (Clasificador)</a></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:view_lista_base' %}">Ver Lista Base (Clasificador)</a></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:update_lista_base' %}">Actualizar Lista Base (Prod. Sin/C)</a></li>
                  <li><h2>Sugerir Precios</h2></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:sugiere_precios' %}">Sugerir Precios</a></li>
                  <li><i class="fa fa-search"></i><a href="{% url 'food:lista_precios_sugeridos' %}">Listar Precios/Suge.</a></li>

            </ul>
          </div>
        </div>
        {% endblock %}
      </div>
      <div class="col-sm-10 ">
          {% block content %}
          {% endblock %}
      </div>
    </div>

  </div>
<div class="col-sm-10 ">
   {% block PiePaginas %}
   {% endblock PiePaginas %}
</div>
</body>

</html>


<!--
<ul class="submenu">
        <li><a href="">Tops</a></li>
        <li><a href="">Bottoms</a></li>
        <li><a href="">Footwear</a></li>
      </ul>
-->

prices/food/templates/en_construccion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>En construccion</title>
</head>
<body>

</body>
</html>

prices/food/templates/index.html
{% extends "Plantilla_Index.html" %}

{% block content %}
<H1 align="center">Análisis de Precios</H1>

  <p>Bienvenido <em>(Soft. Análisis de Precios)</em></p>


<!--  num_proveedores': num_proveedores, 'num_compradores'  -->
  <p>Num. de Proveedores/Num. Compradores :</p>
  <ul>
    <li><strong>Proveedores:</strong> {{ num_proveedores }}</li>
    <li><strong>Compradores:</strong> {{ num_compradores }}</li>
    <li><strong>Num. Detalle Productos:</strong> {{ num_detalles }}</li>
  </ul>

{% endblock %}